import { TimelineDashboard } from './components/TimelineDashboard';
import { TimelineEvent } from './timelineTypes';

const events: TimelineEvent[] = [
  {
    eventId: 'evt-1',
    timestamp: '2026-01-20T08:00:00Z',
    type: 'workflowExecutionEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    workflowId: 'wf-prep-fruit',
    title: 'Workflow Started: Prep & Fruit',
    description: 'Workflow wf-prep-fruit initiated at facility-01, room rm-clean-a',
    sourceSystem: 'Execution Engine',
  },
  {
    eventId: 'evt-2',
    timestamp: '2026-01-20T08:15:00Z',
    type: 'telemetryEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    title: 'Telemetry: Room Temperature Nominal',
    description: 'Temperature 22.5°C, humidity 65% at rm-clean-a',
    sourceSystem: 'Telemetry Engine',
  },
  {
    eventId: 'evt-3',
    timestamp: '2026-01-20T09:30:00Z',
    type: 'resourceAllocationEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    title: 'Resource Allocated: Agar Media',
    description: 'Agar media (res-agar) allocated to workflow wf-prep-fruit',
    sourceSystem: 'Resource Engine',
  },
  {
    eventId: 'evt-4',
    timestamp: '2026-01-20T10:45:00Z',
    type: 'environmentalException',
    severity: 'high',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    title: 'Environmental Alert: Temperature Rise',
    description: 'Temperature exceeded threshold: 28.2°C detected in rm-clean-a',
    sourceSystem: 'Telemetry Engine',
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-5',
    timestamp: '2026-01-20T10:50:00Z',
    type: 'deviation',
    severity: 'high',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    title: 'Deviation Logged: Room Over-Temperature',
    description: 'Deviation dev-alpha-1 created: environmental threshold breach in rm-clean-a',
    sourceSystem: 'Compliance Engine',
    linkedIds: ['evt-4'],
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-6',
    timestamp: '2026-01-20T11:00:00Z',
    type: 'SOPChange',
    severity: 'medium',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    title: 'SOP Referenced: Emergency HVAC Stabilization',
    description: 'SOP sop-alpha-template section: HVAC emergency stabilization invoked',
    sourceSystem: 'SOP Engine',
    linkedIds: ['evt-5'],
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-7',
    timestamp: '2026-01-20T11:30:00Z',
    type: 'telemetryEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    title: 'Telemetry: Temperature Stabilized',
    description: 'Temperature returned to 23.1°C after HVAC adjustment',
    sourceSystem: 'Telemetry Engine',
    linkedIds: ['evt-4'],
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-8',
    timestamp: '2026-01-20T12:00:00Z',
    type: 'CAPAAction',
    severity: 'medium',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    title: 'CAPA Logged: Replace HVAC Filter',
    description: 'CAPA capa-alpha-1: Replace HVAC filter to prevent future overtemp incidents',
    sourceSystem: 'Compliance Engine',
    linkedIds: ['evt-5'],
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-9',
    timestamp: '2026-01-20T13:00:00Z',
    type: 'complianceEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    title: 'Compliance: Incident Summary Recorded',
    description: 'Compliance event comp-alpha-1: Temperature excursion and resolution documented',
    sourceSystem: 'Compliance Engine',
    linkedIds: ['evt-5', 'evt-8'],
    incidentThreadId: 'incident-2026-01-20-facility-01',
  },
  {
    eventId: 'evt-10',
    timestamp: '2026-01-20T14:15:00Z',
    type: 'forecastGeneration',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    title: 'Forecast Updated: Alpha Yield Projection',
    description: 'Forecast forecast-alpha regenerated post-incident for rm-clean-a',
    sourceSystem: 'Forecasting Engine',
  },
  {
    eventId: 'evt-11',
    timestamp: '2026-01-20T15:00:00Z',
    type: 'workflowExecutionEvent',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    roomId: 'rm-clean-a',
    workflowId: 'wf-prep-fruit',
    title: 'Workflow Resumed: Prep & Fruit',
    description: 'Workflow wf-prep-fruit resumed after environmental stabilization',
    sourceSystem: 'Execution Engine',
  },
  {
    eventId: 'evt-12',
    timestamp: '2026-01-20T16:30:00Z',
    type: 'sandboxScenarioRun',
    severity: 'info',
    tenantId: 'tenant-alpha',
    facilityId: 'facility-01',
    title: 'Sandbox Scenario: Temperature Excursion Recovery',
    description: 'Sandbox sandbox-alpha tested recovery protocol post-incident',
    sourceSystem: 'Sandbox Engine',
  },
];

export default function TimelinePage() {
  return <TimelineDashboard events={events} tenantId="tenant-alpha" federatedTenantIds={['tenant-beta']} />;
}
